/* Base d'énigmes v2 — ~330 énigmes, 30 catégories.
   Format : ['CATÉGORIE','SOLUTION'] — ajoutez librement vos lignes !
   Astuce : guillemets doubles "..." si la solution contient une apostrophe. */
const PUZZLES=[
/* ---- CINÉMA ---- */
['CINÉMA','LA VIE EST BELLE'],['CINÉMA','INTOUCHABLES'],['CINÉMA','LE GRAND BLEU'],['CINÉMA','LA GRANDE VADROUILLE'],
['CINÉMA','LES BRONZÉS FONT DU SKI'],['CINÉMA',"LE FABULEUX DESTIN D'AMÉLIE POULAIN"],['CINÉMA','TITANIC'],['CINÉMA','LE ROI LION'],
['CINÉMA','LES CHORISTES'],['CINÉMA','STAR WARS'],['CINÉMA','JURASSIC PARK'],['CINÉMA',"BIENVENUE CHEZ LES CH'TIS"],
['CINÉMA','LE DÎNER DE CONS'],['CINÉMA','LA CITÉ DE LA PEUR'],['CINÉMA','AVATAR'],['CINÉMA','INCEPTION'],['CINÉMA','RETOUR VERS LE FUTUR'],
/* ---- GASTRONOMIE ---- */
['GASTRONOMIE','BŒUF BOURGUIGNON'],['GASTRONOMIE','RATOUILLE'],['GASTRONOMIE','GRATIN DAUPHINOIS'],['GASTRONOMIE','TARTE TATIN'],
['GASTRONOMIE','CROQUE-MONSIEUR'],['GASTRONOMIE','COQ AU VIN'],['GASTRONOMIE','MOUSSE AU CHOCOLAT'],['GASTRONOMIE','CRÊPE SUZETTE'],
['GASTRONOMIE','PLATEAU DE FRUITS DE MER'],['GASTRONOMIE','BAGUETTE TRADITION'],['GASTRONOMIE',"SOUPE À L'OIGNON"],['GASTRONOMIE','CASSOULET DE TOULOUSE'],
['GASTRONOMIE','BLANQUETTE DE VEAU'],['GASTRONOMIE','ÎLE FLOTTANTE'],['GASTRONOMIE','FONDUE SAVOYARDE'],['GASTRONOMIE','QUICHE LORRAINE'],['GASTRONOMIE','CLAFOUTIS AUX CERISES'],
/* ---- FROMAGES DE FRANCE ---- */
['FROMAGES','CAMEMBERT DE NORMANDIE'],['FROMAGES','ROQUEFORT'],['FROMAGES','COMTÉ AFFINÉ'],['FROMAGES','CROTIN DE CHAVIGNOL'],
['FROMAGES',"BLEU D'AUVERGNE"],['FROMAGES',"MONT D'OR"],['FROMAGES','RACLETTE FUMÉE'],['FROMAGES','BRIE DE MEAUX'],['FROMAGES','CANTAL'],['FROMAGES','MORBIER'],
/* ---- EXPRESSIONS CÉLÈBRES ---- */
['EXPRESSION CÉLÈBRE','AU FUR ET À MESURE'],['EXPRESSION CÉLÈBRE','ON A TOUS LE DROIT'],['EXPRESSION CÉLÈBRE','AVOIR LE CAFARD'],
['EXPRESSION CÉLÈBRE','POSER UN LAPIN'],['EXPRESSION CÉLÈBRE','TOMBER DANS LES POMMES'],['EXPRESSION CÉLÈBRE','LES DOIGTS DANS LE NEZ'],
['EXPRESSION CÉLÈBRE','QUAND LES POULES AURONT DES DENTS'],['EXPRESSION CÉLÈBRE','IL PLEUT DES CORDES'],['EXPRESSION CÉLÈBRE',"FAIRE D'UNE PIERRE DEUX COUPS"],
['EXPRESSION CÉLÈBRE','AVOIR LA MAIN VERTE'],['EXPRESSION CÉLÈBRE','CHERCHER MIDI À QUATORZE HEURES'],['EXPRESSION CÉLÈBRE',"HEUREUX COMME UN POISSON DANS L'EAU"],
['EXPRESSION CÉLÈBRE','MÉNAGER LA CHÈVRE ET LE CHOU'],['EXPRESSION CÉLÈBRE',"AVOIR UN CŒUR D'ARTICHAUT"],['EXPRESSION CÉLÈBRE',"AVOIR LE COMPAS DANS L'ŒIL"],
['EXPRESSION CÉLÈBRE','METTRE SON GRAIN DE SEL'],['EXPRESSION CÉLÈBRE',"C'EST LE BOUQUET"],
/* ---- PROVERBES ---- */
['PROVERBE','RIEN NE SERT DE COURIR IL FAUT PARTIR À POINT'],['PROVERBE','QUI SÈME LE VENT RÉCOLTE LA TEMPÊTE'],
['PROVERBE','APRÈS LA PLUIE LE BEAU TEMPS'],['PROVERBE',"IL FAUT BATTRE LE FER TANT QU'IL EST CHAUD"],
['PROVERBE',"PETIT À PETIT L'OISEAU FAIT SON NID"],['PROVERBE','TOUT VIENT À POINT À QUI SAIT ATTENDRE'],
['PROVERBE',"L'HABIT NE FAIT PAS LE MOINE"],['PROVERBE',"CHAT ÉCHAUDÉ CRAINT L'EAU FROIDE"],
['PROVERBE','QUI VEUT VOYAGER LOIN MÉNAGE SA MONTURE'],['PROVERBE',"UN TIENS VAUT MIEUX QUE DEUX TU L'AURAS"],
['PROVERBE',"ON NE FAIT PAS D'OMELETTE SANS CASSER D'ŒUFS"],['PROVERBE',"IL N'Y A PAS DE FUMÉE SANS FEU"],['PROVERBE','LES MURS ONT DES OREILLES'],
/* ---- MUSIQUE ---- */
['MUSIQUE','LES CHAMPS-ÉLYSÉES'],['MUSIQUE','LA VIE EN ROSE'],['MUSIQUE','DERNIÈRE DANSE'],['MUSIQUE','PAPAOUTAI'],
['MUSIQUE','TOI PLUS MOI'],['MUSIQUE','MISTRAL GAGNANT'],['MUSIQUE',"L'AIGLE NOIR"],['MUSIQUE','RÉSISTE'],
['MUSIQUE','PIANO À QUEUE'],['MUSIQUE','CLÉ DE SOL'],['MUSIQUE','GAMME MAJEURE'],['MUSIQUE','ACCORD PARFAIT'],
['MUSIQUE','ACCORDÉON MUSETTE'],['MUSIQUE','GUITARE ÉLECTRIQUE'],['MUSIQUE','ORCHESTRE SYMPHONIQUE'],['MUSIQUE','VINYLE 33 TOURS'],
/* ---- DANSE ---- */
['DANSE','VALSE À TROIS TEMPS'],['DANSE','TANGO ARGENTIN'],['DANSE','ROCK AND ROLL'],['DANSE','HIP-HOP'],
['DANSE',"BALLET DE L'OPÉRA"],['DANSE','FLAMENCO'],['DANSE','CLAQUETTES'],['DANSE','BREAKDANCE'],['DANSE','QUADRILLE'],['DANSE','SALSA CUBAINE'],
/* ---- SPORT ---- */
['SPORT','CARTON ROUGE'],['SPORT','HORS-JEU'],['SPORT','TIR AU BUT'],['SPORT','COUP FRANC'],
['SPORT','MAILLOT JAUNE'],['SPORT','TERRE BATTUE'],['SPORT','DOUBLE FAUTE'],['SPORT','SÉANCE DE TIRS AU BUT'],
['SPORT','PETIT PONT'],['SPORT','LUCARNE OPPOSÉE'],['SPORT','SAUT EN LONGUEUR'],['SPORT','ESCRIME'],['SPORT','JUDO IPPON'],['SPORT','PÉTANQUE'],['SPORT','SURF'],['SPORT','BIATHLON'],
/* ---- TÉLÉVISION ---- */
['TÉLÉVISION','JOURNAL DE VINGT HEURES'],['TÉLÉVISION','QUESTION POUR UN CHAMPION'],['TÉLÉVISION','FORT BOYARD'],['TÉLÉVISION','KOH-LANTA'],
['TÉLÉVISION','LES GUIGNOLS'],['TÉLÉVISION','UN DÎNER PRESQUE PARFAIT'],['TÉLÉVISION','LA ROUE DE LA FORTUNE'],['TÉLÉVISION','FAMILLE EN OR'],
['TÉLÉVISION','BULLETIN MÉTÉO'],['TÉLÉVISION','SÉRIE POLICIÈRE'],['TÉLÉVISION','DOCUMENTAIRE ANIMALIER'],
/* ---- DESSINS ANIMÉS ---- */
['DESSINS ANIMÉS','LES AVENTURES DE TINTIN'],['DESSINS ANIMÉS','ASTÉRIX ET OBÉLIX'],['DESSINS ANIMÉS','LUCKY LUKE'],['DESSINS ANIMÉS','LES SCHTROUMPFS'],
['DESSINS ANIMÉS','LA REINE DES NEIGES'],['DESSINS ANIMÉS','KUNG FU PANDA'],['DESSINS ANIMÉS','TOY STORY'],['DESSINS ANIMÉS','LE VOYAGE DE CHIHIRO'],
['DESSINS ANIMÉS','LES ARISTOCHATS'],['DESSINS ANIMÉS','MON VOISIN TOTORO'],['DESSINS ANIMÉS','ALADDIN'],
/* ---- LITTÉRATURE ---- */
['LITTÉRATURE','LES MISÉRABLES'],['LITTÉRATURE','LE PETIT PRINCE'],['LITTÉRATURE','MADAME BOVARY'],['LITTÉRATURE','LES FLEURS DU MAL'],
['LITTÉRATURE','VINGT MILLE LIEUES SOUS LES MERS'],['LITTÉRATURE','LE COMTE DE MONTE-CRISTO'],['LITTÉRATURE','CYRANO DE BERGERAC'],['LITTÉRATURE','LES TROIS MOUSQUETAIRES'],
['LITTÉRATURE','LE PETIT NICOLAS'],['LITTÉRATURE','RECUEIL DE POÉSIES'],['LITTÉRATURE','FABLE DE LA FONTAINE'],['LITTÉRATURE','ROMAN POLICIER'],['LITTÉRATURE','BANDE DESSINÉE'],
/* ---- HISTOIRE ---- */
['HISTOIRE','PRISE DE LA BASTILLE'],['HISTOIRE','COURONNEMENT DE NAPOLÉON'],['HISTOIRE','DÉBARQUEMENT DE NORMANDIE'],
['HISTOIRE','CHUTE DU MUR DE BERLIN'],['HISTOIRE','SIGNATURE DU TRAITÉ DE ROME'],['HISTOIRE','SACRE DE CHARLEMAGNE'],
['HISTOIRE',"PHARAON D'ÉGYPTE"],['HISTOIRE','CHEVALIERS DE LA TABLE RONDE'],['HISTOIRE','RÉVOLUTION FRANÇAISE'],['HISTOIRE','EMPIRE ROMAIN'],
/* ---- SCIENCES & NATURE ---- */
['SCIENCES','PHOTOSYNTHÈSE'],['SCIENCES','ÉRUPTION VOLCANIQUE'],['SCIENCES',"CYCLE DE L'EAU"],['SCIENCES','GRAVITÉ UNIVERSELLE'],
['SCIENCES','ÉLECTRICITÉ STATIQUE'],['SCIENCES','ARC-EN-CIEL APRÈS LA PLUIE'],['SCIENCES','TREMBLEMENT DE TERRE'],['SCIENCES','HIBERNATION'],['SCIENCES','ATOME'],['SCIENCES','ROBOT'],
/* ---- ESPACE & ASTRONOMIE ---- */
['ESPACE','STATION SPATIALE INTERNATIONALE'],['ESPACE',"CEINTURE D'ASTÉROÏDES"],['ESPACE',"UN PETIT PAS POUR L'HOMME"],
['ESPACE','TÉLESCOPE SPATIAL'],['ESPACE','ÉCLIPSE SOLAIRE'],['ESPACE','LA PLANÈTE ROUGE'],['ESPACE','AURORE BORÉALE'],['ESPACE','COMÈTE DE HALLEY'],
['ESPACE','SATURNE ET SES ANNEAUX'],['ESPACE','APESANTEUR'],['ESPACE','FUSÉE'],['ESPACE','LUNE'],
/* ---- CORPS HUMAIN ---- */
['CORPS HUMAIN',"POMME D'ADAM"],['CORPS HUMAIN','GLOBE OCULAIRE'],['CORPS HUMAIN','COLONNE VERTÉBRALE'],['CORPS HUMAIN','CAGE THORACIQUE'],
['CORPS HUMAIN','DENTS DE SAGESSE'],['CORPS HUMAIN','CORDES VOCALES'],['CORPS HUMAIN','SYSTÈME IMMUNITAIRE'],['CORPS HUMAIN','EMPREINTES DIGITALES'],['CORPS HUMAIN','LA CHAIR DE POULE'],['CORPS HUMAIN','GENOU'],
/* ---- ARTS & PEINTURE ---- */
['ARTS','LA JOCONDE'],['ARTS','LES TOURNESOLS'],['ARTS',"PEINTURE À L'HUILE"],['ARTS','CHEVALET ET PALETTE'],
['ARTS','AQUARELLE'],['ARTS','MUSÉE DU LOUVRE'],['ARTS','ART CONTEMPORAIN'],['ARTS','SCULPTURE SUR BOIS'],['ARTS','GRAFFITI URBAIN'],['ARTS','CLAIR-OBSCUR'],['ARTS','PINCEAU'],
/* ---- ARCHITECTURE ---- */
['ARCHITECTURE','ARC DE TRIOMPHE'],['ARCHITECTURE','VITRAIL DE CATHÉDRALE'],['ARCHITECTURE','PONT SUSPENDU'],['ARCHITECTURE','GRATTE-CIEL NEW-YORKAIS'],
['ARCHITECTURE','COLOMBAGE ALSACIEN'],['ARCHITECTURE','ESCALIER EN SPIRALE'],['ARCHITECTURE','TERRASSE PANORAMIQUE'],['ARCHITECTURE','PHARE DU BOUT DU MONDE'],['ARCHITECTURE','MOULIN À VENT'],['ARCHITECTURE','CHÂTEAU'],
/* ---- LIEUX & VOYAGES ---- */
['LIEUX & VOYAGES','TOUR EIFFEL'],['LIEUX & VOYAGES','MONT SAINT-MICHEL'],['LIEUX & VOYAGES','MURAILLE DE CHINE'],
['LIEUX & VOYAGES','GRAND CANYON'],['LIEUX & VOYAGES','CANAL DE PANAMA'],['LIEUX & VOYAGES','DÉSERT DU SAHARA'],
['LIEUX & VOYAGES','BAIE DE HALONG'],['LIEUX & VOYAGES','CHÂTEAU DE VERSAILLES'],['LIEUX & VOYAGES','OPÉRA DE SYDNEY'],['LIEUX & VOYAGES','PLAGE DE COPACABANA'],
['LIEUX & VOYAGES','FJORD NORVÉGIEN'],['LIEUX & VOYAGES',"TEMPLE D'ANGKOR"],['LIEUX & VOYAGES','CHUTES DU NIAGARA'],
/* ---- MER & OCÉAN ---- */
['MER','GRANDE BARRIÈRE DE CORAIL'],['MER','PHARE DANS LA TEMPÊTE'],['MER','PORT DE PLAISANCE'],['MER','PROFONDEURS ABYSSALES'],
['MER','ÉCUME DES VAGUES'],['MER',"MARÉE D'ÉQUINOXE"],['MER','ÎLE DÉSERTE'],['MER','TRIDENT DE POSÉIDON'],['MER','BATEAU'],
/* ---- MONTAGNE ---- */
['MONTAGNE','SOMMET DU MONT BLANC'],['MONTAGNE','REMONTE-PENTE'],['MONTAGNE','CHALET SUISSE'],['MONTAGNE','RANDONNÉE ALPESTRE'],
['MONTAGNE',"DANGER D'AVALANCHE"],['MONTAGNE','PISTE NOIRE'],['MONTAGNE',"REFUGE D'ALTITUDE"],['MONTAGNE',"L'ABOMINABLE HOMME DES NEIGES"],
['MONTAGNE','CRAMPONS ET PIOLET'],['MONTAGNE','ALPAGE FLEURI'],['MONTAGNE','NEIGE'],
/* ---- ANIMAUX ---- */
['ANIMAUX','AIGLE ROYAL'],['ANIMAUX','PANDA GÉANT'],['ANIMAUX','LOUP GRIS'],['ANIMAUX','RENARD ROUX'],
['ANIMAUX','BALEINE À BOSSE'],['ANIMAUX','PERROQUET GRIS DU GABON'],['ANIMAUX','ABEILLE OUVRIÈRE'],['ANIMAUX','TORTUE DES GALAPAGOS'],
['ANIMAUX',"HÉRISSON D'EUROPE"],['ANIMAUX','FOURMI ROUGE'],['ANIMAUX','DAUPHIN DE LA BAIE'],['ANIMAUX','KANGOUROU BOXEUR'],
['ANIMAUX','PARESSEUX'],['ANIMAUX','KOALA'],['ANIMAUX','CAMÉLÉON'],['ANIMAUX','LOUTRE'],
/* ---- BOTANIQUE & JARDIN ---- */
['JARDIN','ROSIER GRIMPANT'],['JARDIN','PLANTE CARNIVORE'],['JARDIN','BONSAÏ'],['JARDIN','JARDIN POTAGER'],
['JARDIN','SERRE TROPICALE'],['JARDIN','HAIE DE LAURIERS'],['JARDIN','SEMIS DE PRINTEMPS'],['JARDIN','ARROSAGE GOUTTE À GOUTTE'],['JARDIN','HERBIER'],['JARDIN','COQUELICOT DES CHAMPS'],['JARDIN','TULIPE'],
/* ---- MÉTIERS ---- */
['MÉTIERS','BOULANGER PÂTISSIER'],['MÉTIERS','SAPEUR-POMPIER'],['MÉTIERS','CONDUCTEUR DE TRAIN'],['MÉTIERS',"CHEF D'ORCHESTRE"],
['MÉTIERS','AIGUILLEUR DU CIEL'],['MÉTIERS','GARDE CHAMPÊTRE'],['MÉTIERS','SOUFFLEUR DE VERRE'],['MÉTIERS','MAÎTRE FROMAGER'],
['MÉTIERS','HORLOGER'],['MÉTIERS','ŒNOLOGUE'],['MÉTIERS','SAGE-FEMME'],['MÉTIERS','TAPISSIER'],
/* ---- MODE & BEAUTÉ ---- */
['MODE','PETITE ROBE NOIRE'],['MODE','HAUTE COUTURE'],['MODE','PARFUM DE GRASSE'],['MODE','ROUGE À LÈVRES'],
['MODE','DÉFILÉ DE MODE'],['MODE','TAILLEUR CINTRÉ'],['MODE','BOUTIQUE VINTAGE'],['MODE','SOIN DU VISAGE'],['MODE','TRENCH IMPERMÉABLE'],['MODE','CHAPEAU'],
/* ---- JEUX & JOUETS ---- */
['JEUX','CACHE-CACHE'],['JEUX','PETITS CHEVAUX'],['JEUX','PUZZLE DE MILLE PIÈCES'],['JEUX','MARELLE'],
['JEUX','JEU DE BILLES'],['JEUX','COLIN-MAILLARD'],['JEUX','BRIQUES DE CONSTRUCTION'],['JEUX','PATIN À ROULETTES'],['JEUX','CERF-VOLANT'],['JEUX','YO-YO'],
/* ---- FÊTES & TRADITIONS ---- */
['FÊTES',"FEUX D'ARTIFICE DU 14 JUILLET"],['FÊTES','ARBRE DE NOËL'],['FÊTES','CHASSE AUX ŒUFS DE PÂQUES'],['FÊTES','CARNAVAL DE NICE'],
['FÊTES','FÊTE DE LA MUSIQUE'],['FÊTES',"POISSON D'AVRIL"],['FÊTES','BRIN DE MUGUET'],['FÊTES','GALETTE DES ROIS'],['FÊTES',"CITROUILLE D'HALLOWEEN"],['FÊTES','FEU DE LA SAINT-JEAN'],['FÊTES','CADEAU'],
/* ---- TRANSPORTS ---- */
['TRANSPORTS','TRAIN À GRANDE VITESSE'],['TRANSPORTS','MONTGOLFIÈRE'],['TRANSPORTS','VÉLO ÉLECTRIQUE'],['TRANSPORTS','MÉTRO PARISIEN'],
['TRANSPORTS','PAQUEBOT DE CROISIÈRE'],['TRANSPORTS','AUTO-STOP'],['TRANSPORTS','EMBOUTEILLAGE DU WEEK-END'],['TRANSPORTS','PERMIS DE CONDUIRE'],['TRANSPORTS','QUAI DE GARE'],['TRANSPORTS','TÉLÉPHÉRIQUE'],['TRANSPORTS','GARE'],
/* ---- TECHNOLOGIE ---- */
['TECHNOLOGIE','INTELLIGENCE ARTIFICIELLE'],['TECHNOLOGIE','FIBRE OPTIQUE'],['TECHNOLOGIE','RÉSEAU SOCIAL'],
['TECHNOLOGIE','MOT DE PASSE OUBLIÉ'],['TECHNOLOGIE','ÉCRAN TACTILE'],['TECHNOLOGIE','RÉALITÉ VIRTUELLE'],['TECHNOLOGIE','INFORMATIQUE EN NUAGE'],
['TECHNOLOGIE','ROBOT ASPIRATEUR'],['TECHNOLOGIE','DRONE CIVIL'],['TECHNOLOGIE','IMPRESSION 3D'],['TECHNOLOGIE','RÉALITÉ AUGMENTÉE'],['TECHNOLOGIE','CLAVIER'],
/* ---- OUTILS & BRICOLAGE ---- */
['BRICOLAGE','TOURNEVIS CRUCIFORME'],['BRICOLAGE','PERCEUSE À PERCUSSION'],['BRICOLAGE','NIVEAU À BULLE'],['BRICOLAGE','BOÎTE À OUTILS'],
['BRICOLAGE','PAPIER DE VERRE'],['BRICOLAGE',"ÉTABLI D'ATELIER"],['BRICOLAGE','CLÉ À MOLETTE'],['BRICOLAGE','RUBAN ADHÉSIF'],['BRICOLAGE','ESCABEAU'],['BRICOLAGE','COLLE FORTE'],['BRICOLAGE','MARTEAU'],
/* ---- SUPERSTITIONS ---- */
['SUPERSTITIONS','TRÈFLE À QUATRE FEUILLES'],['SUPERSTITIONS','MIROIR BRISÉ'],['SUPERSTITIONS','FER À CHEVAL'],['SUPERSTITIONS','VENDREDI TREIZE'],
['SUPERSTITIONS','ÉTOILE FILANTE'],['SUPERSTITIONS','PATTE DE LAPIN'],['SUPERSTITIONS','CHAT NOIR'],['SUPERSTITIONS','JETER UN SORT'],['SUPERSTITIONS','AMULETTE']
];

/* ---- GRANDE FINALE (énigmes courtes) ---- */
const FINALE=[
['VIE QUOTIDIENNE','MAISON'],['VIE QUOTIDIENNE','CERISE'],['VIE QUOTIDIENNE','MOULIN'],['VIE QUOTIDIENNE','PLAGE'],
['VIE QUOTIDIENNE','BOUTEILLE'],['VIE QUOTIDIENNE','JARDIN'],['VIE QUOTIDIENNE','NUAGE'],['VIE QUOTIDIENNE','TABLEAU'],
['ANIMAUX','CHEVAL'],['ANIMAUX','LUMIÈRE'],['ANIMAUX','DAUPHIN'],['ANIMAUX','KOALA'],
['MUSIQUE','GUITARE'],['MUSIQUE','VIOLON'],['MUSIQUE','TAMBOUR'],
['GASTRONOMIE','FROMAGE'],['GASTRONOMIE','CROISSANT'],['GASTRONOMIE','MOUTARDE'],
['SPORT','VÉLO'],['SPORT','ESCALADE'],['SPORT','RAQUETTE'],
['LIEUX','PARIS'],['LIEUX','MEXIQUE'],['LIEUX','VENISE'],
['EXPRESSION','PRENDRE LE LARGE'],['EXPRESSION','FAIRE LA FÊTE'],['EXPRESSION','COUPER LA POIRE EN DEUX'],
['MÉTIERS','MAGICIEN'],['MÉTIERS','PLOMBIER'],
['ESPACE','FUSÉE'],['ESPACE','LUNE'],['CORPS HUMAIN','GENOU'],['SCIENCES','ATOME'],['SCIENCES','ROBOT'],
['MER','BATEAU'],['MONTAGNE','NEIGE'],['JARDIN','TULIPE'],['FROMAGES','BRIE'],['DANSE','TANGO'],['JEUX','YO-YO'],
['FÊTES','CADEAU'],['TRANSPORTS','GARE'],['BRICOLAGE','MARTEAU'],['MODE','CHAPEAU'],['ARTS','PINCEAU'],
['HISTOIRE','CHÂTEAU'],['LITTÉRATURE','POÈME'],['TECHNOLOGIE','CLAVIER']
];